### ISSUE TITLE
NullPointerException on too many arguments for command

### ISSUE THREAD

**Issue by KennethWussmann** [KennethWussmann/Levitate#1]
Example Syntax: /test <string>
User Input: /test a b c
Throws NullPointerException:
```
Caused by: java.lang.NullPointerException
        at eu.blackwoods.levitate.CommandInformation.matches(CommandInformation.java:207) ~[?:?]
        at eu.blackwoods.levitate.CommandRegistry.playerPassCommand(CommandRegistry.java:267) ~[?:?]
        at eu.blackwoods.levitate.CommandRegistry$1.execute(CommandRegistry.java:119) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar
```

**Comment by KennethWussmann** [comment]
Fixed in [v1.4.1](https://github.com/KennethWussmann/Levitate/releases/tag/v1.4.1)
